# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='memo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
