# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vc', '0002_userinfo_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='Age',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='CreateDate',
            field=models.DateTimeField(default='2017-07-6'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='Gender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='memotxt',
            field=models.TextField(default='xxxx'),
        ),
    ]
