# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vc', '0003_auto_20170706_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='CreateDate',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='memotxt',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='typeid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vc.UserType'),
            preserve_default=False,
        ),
    ]
