# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vc', '0006_group_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Args',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20, null=True)),
                ('Not_Name', models.CharField(max_length=20)),
            ],
        ),
    ]
