# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vc', '0012_auto_20171102_1348'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Milestone',
            new_name='task_id',
        ),
    ]
