# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vc', '0013_auto_20171102_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='urun_task_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.CharField(max_length=500)),
                ('vmlist', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='task_id',
        ),
    ]
