# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vc', '0014_auto_20171102_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='ps_netlabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netlabel', models.CharField(max_length=500)),
            ],
        ),
    ]
