# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vc', '0015_ps_netlabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ps_datastore_host_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datastore', models.CharField(max_length=500)),
                ('esxi', models.CharField(max_length=500)),
            ],
        ),
    ]
